{{- if (index .Values "vertical-pod-autoscaler").updater.verticalPodAutoscaler.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.updater.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  resourcePolicy:
    containerPolicies:
    - containerName: updater
      {{- with (index .Values "vertical-pod-autoscaler").updater.verticalPodAutoscaler.containerPolicies }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  updatePolicy:
    updateMode: Auto
{{- end }}
