{{- if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" -}}
{{- if index .Values "vertical-pod-autoscaler" "updater" "verticalPodAutoscaler" "enabled" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    {{- include "vertical-pod-autoscaler.updater.labels" . | nindent 4 }}
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: updater
    {{- if index .Values "vertical-pod-autoscaler" "updater" "verticalPodAutoscaler" "containerPolicies" }}
      {{- with index .Values "vertical-pod-autoscaler" "updater" "verticalPodAutoscaler" "containerPolicies" -}}
        {{ tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
    {{- end }}
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  updatePolicy:
    updateMode: Auto
{{- end -}}
{{- end -}}
