apiVersion: v1
appVersion: 0.8.0
description: A Helm chart for vertical-pod-autoscaler
engine: gotpl
home: https://github.com/giantswarm/vertical-pod-autoscaler-app
name: vertical-pod-autoscaler-app
sources:
- https://github.com/kubernetes/autoscaler
version: [[ .Version ]]
