vertical-pod-autoscaler:
  global:
    imageRegistry: docker.io

  nameOverride: ""
  fullnameOverride: ""

  admissionController:
    # Enable the component
    enabled: true

    replicaCount: 2

    image:
      registry: docker.io
      repository: giantswarm/vpa-admission-controller
      tag: 0.13.0
      pullPolicy: IfNotPresent

    pdb:
      create: true

    resources:
      limits:
        cpu: 50m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 200Mi

    verticalPodAutoscaler:
      enabled: true
      containerPolicies:
        controlledResources:
        - cpu
        - memory
        maxAllowed:
          cpu: 200m
          memory: 3000Mi
        minAllowed:
          cpu: 50m
          memory: 200Mi
        mode: Auto

    extraArgs:
      v: 2
      webhook-timeout-seconds: 5

    metrics:
      serviceMonitor:
        # Specifies whether a service monitor should be created
        enabled: true

  recommender:
    replicaCount: 1

    image:
      registry: docker.io
      repository: giantswarm/vpa-recommender
      tag: 0.13.0
      pullPolicy: IfNotPresent

    pdb:
      create: true

    resources:
      limits:
        cpu: 50m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 200Mi

    verticalPodAutoscaler:
      enabled: true
      containerPolicies:
        controlledResources:
        - cpu
        - memory
        maxAllowed:
          cpu: 200m
          memory: 3000Mi
        minAllowed:
          cpu: 50m
          memory: 200Mi
        mode: Auto

    extraArgs:
      pod-recommendation-min-cpu-millicores: 15
      pod-recommendation-min-memory-mb: 100
      v: 2

    metrics:
      serviceMonitor:
        # Specifies whether a service monitor should be created
        enabled: true

  updater:
    # Enable the component
    enabled: true

    replicaCount: 1

    image:
      registry: docker.io
      repository: giantswarm/vpa-updater
      tag: 0.13.0
      pullPolicy: IfNotPresent

    pdb:
      create: true

    resources:
      limits:
        cpu: 50m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 200Mi

    verticalPodAutoscaler:
      enabled: true
      containerPolicies:
        controlledResources:
        - cpu
        - memory
        maxAllowed:
          cpu: 200m
          memory: 3000Mi
        minAllowed:
          cpu: 50m
          memory: 200Mi
        mode: Auto

    extraArgs:
      v: 2
      # min-replicas set to 1 to prevent the updater from throwing errors concerning prometheus only having 1 replica
      min-replicas: 1

    metrics:
      serviceMonitor:
        # Specifies whether a service monitor should be created
        enabled: true
