# Default values for vertical-pod-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Global parameters

global:
  ## @param global.imageRegistry Global Docker image registry
  imageRegistry: gsoci.azurecr.io

vertical-pod-autoscaler:

  ## @section Admission controller parameters

  admissionController:
    ## @param admissionController.replicaCount Number of replicas
    replicaCount: 2

    image:
      ## @param admissionController.image.registry Image registry
      registry: gsoci.azurecr.io

      ## @param admissionController.image.repository Image repository
      repository: giantswarm/vpa-admission-controller

    pdb:
      ## @param admissionController.pdb.create Specifies whether a pod disruption budget should be created
      create: true

    ## @param admissionController.securityContext Container security context
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true

    ## @param admissionController.resources CPU/Memory resource requests/limits
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 250m
        memory: 250Mi

    ## @param admissionController.verticalPodAutoscaler Vertical pod autoscaling
    verticalPodAutoscaler:
      enabled: false
      containerPolicies:
        mode: Auto
        controlledResources:
        - cpu
        - memory
        minAllowed:
          cpu: 250m
          memory: 250Mi

    ## @extra admissionController.extraArgs [object] Additional container arguments
    ## @param admissionController.extraArgs.v Number for the log level verbosity
    extraArgs:
      kube-api-burst: 75
      kube-api-qps: 50
      webhook-timeout-seconds: 5

    metrics:
      serviceMonitor:
        ## @param admissionController.metrics.serviceMonitor.enabled Specifies whether a service monitor should be created
        enabled: true

  ## @section Recommender parameters

  recommender:
    image:
      ## @param recommender.image.registry Image registry
      registry: gsoci.azurecr.io

      ## @param recommender.image.repository Image repository
      repository: giantswarm/vpa-recommender

    ## @param recommender.podAnnotations Additional pod annotations
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

    ## @param recommender.securityContext Container security context
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true

    livenessProbe:
      ## @param recommender.livenessProbe.initialDelaySeconds Delay before the liveness probe is initiated
      initialDelaySeconds: 45

      ## @param recommender.livenessProbe.periodSeconds How often to perform the liveness probe
      periodSeconds: 15

      ## @param recommender.livenessProbe.failureThreshold Minimum consecutive failures for the liveness probe to be considered failed after having succeeded
      failureThreshold: 5

    readinessProbe:
      ## @param recommender.readinessProbe.initialDelaySeconds Delay before the readiness probe is initiated
      initialDelaySeconds: 30

      ## @param recommender.readinessProbe.periodSeconds How often to perform the readiness probe
      periodSeconds: 15

      ## @param recommender.readinessProbe.failureThreshold Minimum consecutive failures for the readiness probe to be considered failed after having succeeded
      failureThreshold: 5

    ## @param recommender.resources CPU/Memory resource requests/limits
    resources:
      requests:
        cpu: 500m
        memory: 250Mi

    ## @param recommender.verticalPodAutoscaler Vertical pod autoscaling
    verticalPodAutoscaler:
      enabled: false
      containerPolicies:
        mode: Auto
        controlledResources:
        - cpu
        - memory
        minAllowed:
          cpu: 250m
          memory: 250Mi

    ## @extra recommender.extraArgs [object] Additional container arguments
    ## @param recommender.extraArgs.v Number for the log level verbosity
    extraArgs:
      # If true, only track pods which have an associated VPA
      memory-saver: true
      # Allow the recommender to execute more requests against the api
      kube-api-burst: 75
      kube-api-qps: 50
      # Double the memory during the next Pod resource update, to speed up the recovery from an OOMKilled
      oom-bump-up-ratio: 2.0
      # The lowest setting for the CPU
      pod-recommendation-min-cpu-millicores: 50
      # This is the recommended default for the memory
      pod-recommendation-min-memory-mb: 250
      # CPU usage percentile that will be used as a base for CPU target recommendation.
      # Doesn't affect CPU lower bound, CPU upper bound nor memory recommendations.
      # Sets however a CPU value which matches the 95% percentile of the workload consumption
      target-cpu-percentile: 0.95

    metrics:
      serviceMonitor:
        ## @param recommender.metrics.serviceMonitor.enabled Specifies whether a service monitor should be created
        enabled: true

  ## @section Updater parameters

  updater:
    image:
      ## @param updater.image.registry Image registry
      registry: gsoci.azurecr.io

      ## @param updater.image.repository Image repository
      repository: giantswarm/vpa-updater

    ## @param updater.podAnnotations Additional pod annotations
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

    ## @param updater.securityContext Container security context
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true

    livenessProbe:
      ## @param updater.livenessProbe.initialDelaySeconds Delay before the liveness probe is initiated
      initialDelaySeconds: 45

      ## @param updater.livenessProbe.periodSeconds How often to perform the liveness probe
      periodSeconds: 15

      ## @param updater.livenessProbe.failureThreshold Minimum consecutive failures for the liveness probe to be considered failed after having succeeded
      failureThreshold: 5

    readinessProbe:
      ## @param updater.readinessProbe.initialDelaySeconds Delay before the readiness probe is initiated
      initialDelaySeconds: 30

      ## @param updater.readinessProbe.periodSeconds How often to perform the readiness probe
      periodSeconds: 15

      ## @param updater.readinessProbe.failureThreshold Minimum consecutive failures for the readiness probe to be considered failed after having succeeded
      failureThreshold: 5

    ## @param updater.resources CPU/Memory resource requests/limits
    resources:
      requests:
        cpu: 500m
        memory: 250Mi

    ## @param updater.verticalPodAutoscaler Vertical pod autoscaling
    verticalPodAutoscaler:
      enabled: false
      containerPolicies:
        mode: Auto
        controlledResources:
        - cpu
        - memory
        minAllowed:
          cpu: 250m
          memory: 250Mi

    ## @extra updater.extraArgs [object] Additional container arguments
    ## @param updater.extraArgs.v Number for the log level verbosity
    extraArgs:
      kube-api-burst: 75
      kube-api-qps: 50
      min-replicas: 1

    metrics:
      serviceMonitor:
        ## @param updater.metrics.serviceMonitor.enabled Specifies whether a service monitor should be created
        enabled: true

  ## @section CRDs parameters

  crds:
    image:
      ## @param crds.image.registry Image registry
      registry: gsoci.azurecr.io

      ## @param crds.image.repository Image repository
      repository: giantswarm/kubectl

      ## @param crds.image.tag Image tag
      tag: 1.29.2

    ## @param crds.securityContext Container security context
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
