vertical-pod-autoscaler:
  nameOverride: ""
  fullnameOverride: ""

  admissionController:
    # Enable the component
    enabled: true

    replicaCount: 2

    image:
      repository: docker.io/giantswarm/vpa-admission-controller
      tag: 0.11.0
      pullPolicy: IfNotPresent

    resources:
      limits:
        cpu: 200m
        memory: 2000Mi
      requests:
        cpu: 50m
        memory: 200Mi

    extraArgs:
      v: 2
      webhook-timeout-seconds: 5

    metrics:
      serviceMonitor:
        # Specifies whether a service monitor should be created
        enabled: true

  recommender:
    replicaCount: 1

    image:
      repository: docker.io/giantswarm/vpa-recommender
      tag: 0.11.0
      pullPolicy: IfNotPresent

    resources:
      limits:
        cpu: 200m
        memory: 3000Mi
      requests:
        cpu: 50m
        memory: 500Mi

    extraArgs:
      pod-recommendation-min-cpu-millicores: 15
      pod-recommendation-min-memory-mb: 100
      v: 2

    metrics:
      serviceMonitor:
        # Specifies whether a service monitor should be created
        enabled: true

  updater:
    # Enable the component
    enabled: true

    replicaCount: 1

    image:
      repository: docker.io/giantswarm/vpa-updater
      tag: 0.11.0
      pullPolicy: IfNotPresent

    resources:
      limits:
        cpu: 200m
        memory: 3000Mi
      requests:
        cpu: 50m
        memory: 500Mi

    extraArgs:
      v: 2

    metrics:
      serviceMonitor:
        # Specifies whether a service monitor should be created
        enabled: true
