version: 2.1
orbs:
  architect: giantswarm/architect@0.17.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push vertical-pod-autoscaler-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "vertical-pod-autoscaler-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
