version: 2.1
orbs:
  architect: giantswarm/architect@4.9.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-to-playground-catalog
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "vertical-pod-autoscaler-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "vertical-pod-autoscaler-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-shared-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "shared-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-aws-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-azure-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-kvm-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-openstack-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "openstack-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
     
      - architect/push-to-app-collection:
          context: architect
          name: push-to-vmware-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "vmware-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
