version: 2.1
orbs:
  architect: giantswarm/architect@2.11.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: playground-catalog
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "vertical-pod-autoscaler-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "vertical-pod-autoscaler-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: shared-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "shared-app-collection"
          disable_force_upgrade: true
          user_configmap_name: "vertical-pod-autoscaler"
          user_configmap_path: "config/vertical-pod-autoscaler.yaml"
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: aws-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          disable_force_upgrade: true
          user_configmap_name: "vertical-pod-autoscaler"
          user_configmap_path: "config/vertical-pod-autoscaler.yaml"
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: azure-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          disable_force_upgrade: true
          user_configmap_name: "vertical-pod-autoscaler"
          user_configmap_path: "config/vertical-pod-autoscaler.yaml"
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: kvm-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          disable_force_upgrade: true
          user_configmap_name: "vertical-pod-autoscaler"
          user_configmap_path: "config/vertical-pod-autoscaler.yaml"
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
              
      - architect/push-to-app-collection:
          context: architect
          name: vmware-app-collection
          app_catalog: "control-plane-catalog"
          app_name: "vertical-pod-autoscaler-app"
          app_namespace: "giantswarm"
          app_collection_repo: "vmware-app-collection"
          disable_force_upgrade: true
          user_configmap_name: "vertical-pod-autoscaler"
          user_configmap_path: "config/vertical-pod-autoscaler.yaml"
          requires:
            - control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
