version: 2.1

orbs:
  architect: giantswarm/architect@6.6.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-catalog
          context: architect
          executor: app-build-suite
          chart: vertical-pod-autoscaler-app
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          persist_chart_archive: true
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          executor: app-build-suite
          chart: vertical-pod-autoscaler-app
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          requires:
            - push-to-default-catalog
          filters:
            branches:
              ignore:
                - main
