apiVersion: v1
kind: ConfigMap
metadata:
  name: vertical-pod-autoscaler
  namespace: giantswarm
data:
  values.yaml: |
    updater:
      extraArgs:
        min-replicas: 1
        v: 2

    admissionController:
      enabled: true
      replicaCount: 2
