apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}-admission-controller
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - ports:
    - port: 8000
      protocol: TCP
    - port: 8944
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
