apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ (index .Values "vertical-pod-autoscaler").admissionController.containerPorts.https }}
    - protocol: TCP
      port: {{ (index .Values "vertical-pod-autoscaler").admissionController.containerPorts.metrics }}
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
