{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vpa-annotate-job-cilium-np
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      job-name: {{ include "vertical-pod-autoscaler.crds.fullname" . }}
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "6443"
{{- end }}
