kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vertical-pod-autoscaler.crds.fullname" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  labels:
    {{- include "vertical-pod-autoscaler.crds.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      job-name: {{ include "vertical-pod-autoscaler.crds.fullname" . }}
  # allow egress traffic to everywhere
  egress:
  - {}
  # deny ingress traffic
  ingress: []
  policyTypes:
  - Egress
  - Ingress
