apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vertical-pod-autoscaler.crds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.crds.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  podSelector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.crds.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
