kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vertical-pod-autoscaler.crds.fullname" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  labels:
    whites: yeah
    {{- include "vertical-pod-autoscaler.crds.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      job-name: {{ include "vertical-pod-autoscaler.crds.fullname" . }}
  # allow egress traffic to the Kubernetes API
  egress:
  - ports:
    - port: 443
      protocol: TCP
    # legacy port kept for compatibility
    - port: 6443
      protocol: TCP
    to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  # deny ingress traffic
  ingress: []
  policyTypes:
  - Egress
  - Ingress
