{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vpa-annotate-job-np
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-7"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
spec:
  egress:
    - toEntities:
        - kube-apiserver
{{- end }}
