apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.crdPatch.fullname" . }}
  labels:
    {{- include "vertical-pod-autoscaler.crdPatch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vertical-pod-autoscaler.crdPatch.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vertical-pod-autoscaler.crdPatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
