{{- if .Capabilities.APIVersions.Has "cilium.io/v2" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "vpa.fullname" . }}-crd-patch
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    # run only on upgrade
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
  labels:
    app.kubernetes.io/component: {{ include "vpa.fullname" . }}-crd-patch
    {{- include "vpa.selectorLabels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "vpa.fullname" . }}-crd-patch
      {{- include "vpa.selectorLabels" . | nindent 4 }}
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "6443"
{{- end }}
