apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vpa.fullname" . }}-crd-patch
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    # run only on upgrade
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app.kubernetes.io/component: {{ include "vpa.fullname" . }}-crd-patch
    {{- include "vpa.selectorLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - delete
- apiGroups:
  - application.giantswarm.io
  resources:
  - charts
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "vpa.fullname" . }}-crd-patch
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa.fullname" . }}-crd-patch
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    # run only on upgrade
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app.kubernetes.io/component: {{ include "vpa.fullname" . }}-crd-patch
    {{- include "vpa.selectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa.fullname" . }}-crd-patch
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.fullname" . }}-crd-patch
    namespace: {{ .Release.Namespace | quote }}
