apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vertical-pod-autoscaler.crdPatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.crdPatch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.crdPatch.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "vertical-pod-autoscaler.crdPatch.fullname" . }}
      containers:
      - name: kubectl
        image: {{ include "common.images.image" ( dict "imageRoot" (index .Values "vertical-pod-autoscaler").crds.image "global" .Values.global ) }}
        args:
        - annotate
        - customresourcedefinitions.apiextensions.k8s.io
        - verticalpodautoscalers.autoscaling.k8s.io
        - verticalpodautoscalercheckpoints.autoscaling.k8s.io
        - meta.helm.sh/release-name-
        - meta.helm.sh/release-namespace-
        securityContext:
          {{- toYaml (index .Values "vertical-pod-autoscaler").crds.securityContext | nindent 10 }}
      securityContext:
        {{- toYaml (index .Values "vertical-pod-autoscaler").crds.podSecurityContext | nindent 8 }}
      restartPolicy: OnFailure
  backoffLimit: 3
  ttlSecondsAfterFinished: 0
