{{ if not .Values.ciliumNetworkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: vpa-annotate-job-np
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-7"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      job-name: vpa-remove-crd-ownership
  # allow egress traffic to the Kubernetes API
  egress:
  - ports:
    - port: 443
      protocol: TCP
    # legacy port kept for compatibility
    - port: 6443
      protocol: TCP
    to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  # deny ingress traffic
  ingress: []
  policyTypes:
  - Egress
  - Ingress
{{ end }}
