{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vpa-webhook
  labels:
    app.kubernetes.io/component: admission-controller
    {{- include "vpa.labels" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-path: "/metrics"
    giantswarm.io/monitoring-port: metrics
spec:
  ports:
    - port: 443
      name: http
      targetPort: http
    - name: metrics
      port: 8944
      targetPort: metrics
  selector:
    app.kubernetes.io/component: admission-controller
    {{- include "vpa.selectorLabels" . | nindent 4 }}
{{- end }}
