apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: admission-controller
    {{- include "vpa.labels" . | nindent 4 }}
  name: {{ include "vpa.fullname" . }}-admission-controller
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - ports:
    - port: 8000
      protocol: TCP
    - port: 8944
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      {{- include "vpa.labels" . | nindent 6 }}
  policyTypes:
  - Ingress
