{{- if .Values.admissionController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vpa.fullname" . }}-admission-controller
  labels:
    app.kubernetes.io/component: admission-controller
    {{- include "vpa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admissionController.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      {{- include "vpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        giantswarm.io/monitoring-path: "/metrics"
        giantswarm.io/monitoring-port: "metrics"
      labels:
        app.kubernetes.io/component: admission-controller
        {{- include "vpa.labels" . | nindent 8 }}
        giantswarm.io/monitoring: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "vpa.serviceAccountName" . }}-admission-controller
      securityContext:
        {{- toYaml .Values.admissionController.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.admissionController.securityContext | nindent 12 }}
          {{- if (.Values.Installation) }}
          image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.admissionController.image.name }}:{{ .Values.admissionController.image.tag | default .Chart.AppVersion }}"
          {{ else }}
          image: "{{ .Values.image.registry }}/{{ .Values.admissionController.image.name }}:{{ .Values.admissionController.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.admissionController.image.pullPolicy }}
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/tls-certs"
              readOnly: true
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 120
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: metrics
              containerPort: 8944
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.admissionController.resources | nindent 12 }}
      volumes:
        - name: tls-certs
          secret:
            secretName: vpa-tls-certs
      {{- with .Values.admissionController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
