{{- if .Values.admissionController.enabled }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vpa.serviceAccountName" . }}-admission-controller
  labels:
    app.kubernetes.io/component: admission-controller
    {{- include "vpa.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
