{{- if .Values.rbac.create }}

{{- if .Values.recommender.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa.fullname" . }}-metrics-reader
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa.fullname" . }}-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa.fullname" . }}-checkpoint-actor
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa.fullname" . }}-checkpoint-actor
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.updater.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa.fullname" . }}-evictionter-binding
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa.fullname" . }}-evictioner
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa.fullname" . }}-status-reader-binding
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa.fullname" . }}-status-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if or .Values.recommender.enabled .Values.updater.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa.fullname" . }}-actor
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa.fullname" . }}-actor
subjects:
{{- if .Values.recommender.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.updater.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

{{- if coalesce .Values.recommender.enabled .Values.updater.enabled .Values.admissionController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa.fullname" . }}-target-reader-binding
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa.fullname" . }}-target-reader
subjects:
{{- if .Values.recommender.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.admissionController.enabled}}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-admission-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.updater.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

{{- end }}
