apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
  name: {{ include "vertical-pod-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
    - ipBlock:
        cidr: 100.64.0.0/10
  podSelector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress