apiVersion: v1
kind: Service
metadata:
  name: {{ include "vpa.fullname" . }}-recommender
  labels:
    app.kubernetes.io/component: recommender
    {{- include "vpa.labels" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-path: "/metrics"
    giantswarm.io/monitoring-port: "8942"
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 8942
    targetPort: metrics
  selector:
    app.kubernetes.io/component: recommender
    {{- include "vpa.selectorLabels" . | nindent 4 }}
