{{- if .Values.recommender.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vpa.fullname" . }}-recommender
  labels:
    app.kubernetes.io/component: recommender
    {{- include "vpa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.recommender.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: recommender
      {{- include "vpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        giantswarm.io/monitoring-path: "/metrics"
        giantswarm.io/monitoring-port: "metrics"
      labels:
        app.kubernetes.io/component: recommender
        {{- include "vpa.labels" . | nindent 8 }}
        giantswarm.io/monitoring: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "vpa.serviceAccountName" . }}-recommender
      securityContext:
        {{- toYaml .Values.recommender.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.recommender.securityContext | nindent 12 }}
          {{- if (.Values.Installation) }}
          image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.recommender.image.name }}:{{ .Values.recommender.image.tag  | default .Chart.AppVersion }}"
          {{ else }}
          image: "{{ .Values.image.registry }}/{{ .Values.recommender.image.name }}:{{ .Values.recommender.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.recommender.image.pullPolicy }}
          {{- if .Values.recommender.extraArgs }}
          args:
          {{- range $key, $value := .Values.recommender.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          {{- end }}
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 120
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - name: metrics
              containerPort: 8942
              protocol: TCP
          resources:
            {{- toYaml .Values.recommender.resources | nindent 12 }}
      {{- with .Values.recommender.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.recommender.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.recommender.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
